### ISSUE TITLE
parse a remote playlist?

### ISSUE THREAD

**Issue by chovy** [tedconf/node-m3u8#14]
I'd like to parse a remote playlist for a stream that matches a specific bandwidth and/or resolution

Given http://remote-cdn/index.m3u8

```
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1896000,AUDIO="master_broadcast"
http://remote-cdn/1896k.m3u8
```

I'd like to be able to search by BANDWIDTH or RESOLUTION

**Comment by chovy** [comment]
Here's an example stream:

http://nasatv-lh.akamaihd.net/i/NASA_101@319270/master.m3u8

**Comment by chovy** [comment]
I've decided to just save the playlist locally and parse it from the file system.

**Comment by alecananian** [comment]
If anybody needs to do this and doesn't have the option of saving the playlist locally first, I found that you can parse the remote file using the [Needle HTTP client](https://github.com/tomas/needle) (or another client that supports piping to a stream):
    
    const m3u8 = require('m3u8');
    const needle = require('needle');

    const parser = m3u8.createStream();

    parser.on('item', function(item) {
        // emits PlaylistItem, MediaItem, StreamItem, and IframeStreamItem
    });

    parser.on('m3u', function(m3u) {
        // fully parsed m3u file
    });

    needle.get('http://url.m3u8').pipe(parser);
